/* The following code was generated by JFlex 1.4.3 on 5/5/24, 2:54 PM */

package compiladorapp;
import static compiladorapp.Tokens.*;  

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/5/24, 2:54 PM from the specification file
 * <tt>/home/wherethacoffee/NetBeansProjects/CompiladorApp/src/compiladorapp/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\50\1\5"+
    "\2\0\1\44\1\51\1\0\1\60\1\61\1\43\1\42\1\56\1\10"+
    "\1\11\1\4\12\7\1\57\1\53\1\46\1\45\1\47\2\0\3\6"+
    "\1\37\4\6\1\36\2\6\1\35\6\6\1\31\7\6\1\54\1\0"+
    "\1\55\1\0\1\6\1\0\1\22\1\14\1\17\1\27\1\24\1\40"+
    "\1\32\1\41\1\16\2\6\1\15\1\6\1\30\1\26\1\12\1\6"+
    "\1\20\1\25\1\23\1\13\1\21\1\33\1\34\2\6\1\62\1\52"+
    "\1\63\103\0\1\6\7\0\1\6\3\0\1\6\3\0\1\6\1\0"+
    "\1\6\6\0\1\6\1\0\1\6\4\0\1\6\7\0\1\6\3\0"+
    "\1\6\3\0\1\6\1\0\1\6\6\0\1\6\1\0\1\6\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\2\1\4\1\5\1\6"+
    "\1\1\12\4\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\2\1\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\2\1\0\1\27\1\30\1\0"+
    "\3\4\1\31\6\4\1\32\3\4\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\2\4\1\41\7\4\1\42\7\4"+
    "\1\43\1\44\1\45\11\4\1\46\7\4\1\47\1\50"+
    "\2\4\1\51\1\4\1\52\3\4\1\53\1\54\1\55"+
    "\1\56\1\4\1\57\1\4\1\60\2\4\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\320\0\u0104\0\u0138"+
    "\0\u016c\0\u01a0\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8"+
    "\0\u030c\0\u0340\0\u0374\0\u03a8\0\u016c\0\64\0\64\0\u03dc"+
    "\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0\0\64\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u0514\0\320"+
    "\0\64\0\u01a0\0\u01a0\0\u0548\0\u057c\0\u05b0\0\u0104\0\u05e4"+
    "\0\u0618\0\u064c\0\u0680\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784"+
    "\0\u07b8\0\64\0\64\0\64\0\64\0\64\0\64\0\u07ec"+
    "\0\u0820\0\u0104\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958"+
    "\0\u098c\0\u0104\0\u09c0\0\u09f4\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4"+
    "\0\u0af8\0\u0104\0\u0104\0\u0104\0\u0b2c\0\u0b60\0\u0b94\0\u0bc8"+
    "\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\u0104\0\u0d00\0\u0d34"+
    "\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04\0\u0e38\0\u0104\0\u0104\0\u0e6c"+
    "\0\u0ea0\0\u0104\0\u0ed4\0\u0104\0\u0f08\0\u0f3c\0\u0f70\0\u0104"+
    "\0\u0104\0\u0104\0\u0104\0\u0fa4\0\u0104\0\u0fd8\0\u0104\0\u100c"+
    "\0\u1040\0\u0104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\3\7\1\14\1\15\1\7\1\16\2\7"+
    "\1\17\1\20\1\7\1\21\1\22\1\23\1\7\1\24"+
    "\6\7\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\66\0\1\4\65\0\1\47\57\0"+
    "\1\50\2\0\2\50\1\51\56\50\6\0\2\7\2\0"+
    "\30\7\31\0\1\10\1\0\1\52\61\0\1\10\1\0"+
    "\1\53\61\0\1\52\62\0\2\7\2\0\1\7\1\54"+
    "\4\7\1\55\21\7\30\0\2\7\2\0\16\7\1\56"+
    "\7\7\1\57\1\7\30\0\2\7\2\0\3\7\1\60"+
    "\4\7\1\61\17\7\30\0\2\7\2\0\14\7\1\62"+
    "\13\7\30\0\2\7\2\0\3\7\1\63\24\7\30\0"+
    "\2\7\2\0\21\7\1\64\6\7\30\0\2\7\2\0"+
    "\12\7\1\65\1\7\1\66\13\7\30\0\2\7\2\0"+
    "\12\7\1\67\15\7\30\0\2\7\2\0\11\7\1\70"+
    "\16\7\30\0\2\7\2\0\27\7\1\71\67\0\1\72"+
    "\63\0\1\73\63\0\1\74\63\0\1\75\67\0\1\76"+
    "\64\0\1\77\11\0\1\47\1\3\1\4\61\47\6\0"+
    "\2\7\2\0\2\7\1\100\25\7\30\0\2\7\2\0"+
    "\4\7\1\101\23\7\30\0\2\7\2\0\11\7\1\102"+
    "\16\7\30\0\2\7\2\0\10\7\1\103\17\7\30\0"+
    "\2\7\2\0\13\7\1\104\14\7\30\0\2\7\2\0"+
    "\4\7\1\105\23\7\30\0\2\7\2\0\13\7\1\106"+
    "\14\7\30\0\2\7\2\0\4\7\1\107\23\7\30\0"+
    "\2\7\2\0\26\7\1\110\1\7\30\0\2\7\2\0"+
    "\1\7\1\111\26\7\30\0\2\7\2\0\21\7\1\112"+
    "\1\113\5\7\30\0\2\7\2\0\6\7\1\114\21\7"+
    "\30\0\2\7\2\0\4\7\1\115\23\7\30\0\2\7"+
    "\2\0\3\7\1\116\24\7\30\0\2\7\2\0\7\7"+
    "\1\117\6\7\1\120\11\7\30\0\2\7\2\0\13\7"+
    "\1\121\14\7\30\0\2\7\2\0\12\7\1\122\15\7"+
    "\30\0\2\7\2\0\15\7\1\123\12\7\30\0\2\7"+
    "\2\0\12\7\1\124\15\7\30\0\2\7\2\0\11\7"+
    "\1\125\16\7\30\0\2\7\2\0\10\7\1\126\17\7"+
    "\30\0\2\7\2\0\2\7\1\127\25\7\30\0\2\7"+
    "\2\0\11\7\1\130\16\7\30\0\2\7\2\0\4\7"+
    "\1\131\23\7\30\0\2\7\2\0\3\7\1\132\24\7"+
    "\30\0\2\7\2\0\4\7\1\133\23\7\30\0\2\7"+
    "\2\0\10\7\1\134\17\7\30\0\2\7\2\0\11\7"+
    "\1\135\16\7\30\0\2\7\2\0\13\7\1\136\14\7"+
    "\30\0\2\7\2\0\5\7\1\137\22\7\30\0\2\7"+
    "\2\0\1\7\1\140\26\7\30\0\2\7\2\0\3\7"+
    "\1\141\24\7\30\0\2\7\2\0\23\7\1\142\1\143"+
    "\1\144\2\7\30\0\2\7\2\0\16\7\1\145\11\7"+
    "\30\0\2\7\2\0\12\7\1\146\15\7\30\0\2\7"+
    "\2\0\5\7\1\147\22\7\30\0\2\7\2\0\11\7"+
    "\1\150\16\7\30\0\2\7\2\0\3\7\1\151\24\7"+
    "\30\0\2\7\2\0\27\7\1\152\30\0\2\7\2\0"+
    "\3\7\1\153\24\7\30\0\2\7\2\0\12\7\1\154"+
    "\15\7\30\0\2\7\2\0\4\7\1\155\23\7\30\0"+
    "\2\7\2\0\16\7\1\156\11\7\30\0\2\7\2\0"+
    "\14\7\1\157\13\7\30\0\2\7\2\0\20\7\1\160"+
    "\7\7\30\0\2\7\2\0\12\7\1\161\15\7\30\0"+
    "\2\7\2\0\16\7\1\162\11\7\30\0\2\7\2\0"+
    "\11\7\1\163\16\7\30\0\2\7\2\0\16\7\1\164"+
    "\11\7\30\0\2\7\2\0\11\7\1\165\16\7\30\0"+
    "\2\7\2\0\1\7\1\166\26\7\30\0\2\7\2\0"+
    "\12\7\1\167\15\7\30\0\2\7\2\0\2\7\1\170"+
    "\25\7\30\0\2\7\2\0\3\7\1\171\24\7\30\0"+
    "\2\7\2\0\12\7\1\172\15\7\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4212];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\21\1\2\11\6\1\11\11"+
    "\1\1\1\0\1\11\1\1\1\0\16\1\6\11\73\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[122];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    public int valor, linea, columna, posTabla;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 200) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 38: 
          { lexeme=yytext(); valor=-3; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Class;
          }
        case 50: break;
        case 22: 
          { lexeme=yytext(); valor=-47; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Llave_c;
          }
        case 51: break;
        case 11: 
          { lexeme=yytext(); valor=-30; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Menor_que;
          }
        case 52: break;
        case 39: 
          { lexeme=yytext(); valor=-16; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return While;
          }
        case 53: break;
        case 4: 
          { lexeme=yytext(); valor=-22; linea=yyline+1; columna=yycolumn+1; posTabla=-2; return Identificador;
          }
        case 54: break;
        case 23: 
          { lexeme=yytext(); valor=-20; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return C_String;
          }
        case 55: break;
        case 26: 
          { lexeme=yytext(); valor=-15; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Do;
          }
        case 56: break;
        case 42: 
          { lexeme=yytext(); valor=-6; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Double;
          }
        case 57: break;
        case 36: 
          { lexeme=yytext(); valor=-4; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Void;
          }
        case 58: break;
        case 9: 
          { lexeme=yytext(); valor=-28; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Modulo;
          }
        case 59: break;
        case 37: 
          { lexeme=yytext(); valor=-14; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Else;
          }
        case 60: break;
        case 47: 
          { lexeme=yytext(); valor=-10; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return NextInt;
          }
        case 61: break;
        case 34: 
          { lexeme=yytext(); valor=-8; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return New;
          }
        case 62: break;
        case 19: 
          { lexeme=yytext(); valor=-44; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Parentesis_a;
          }
        case 63: break;
        case 6: 
          { lexeme=yytext(); valor=-25; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Menos;
          }
        case 64: break;
        case 10: 
          { lexeme=yytext(); valor=-29; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Igual;
          }
        case 65: break;
        case 17: 
          { lexeme=yytext(); valor=-42; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Coma;
          }
        case 66: break;
        case 7: 
          { lexeme=yytext(); valor=-24; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Mas;
          }
        case 67: break;
        case 46: 
          { lexeme=yytext(); valor=-19; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Default;
          }
        case 68: break;
        case 5: 
          { lexeme=yytext(); valor=-23; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return C_entera;
          }
        case 69: break;
        case 45: 
          { lexeme=yytext(); valor=-12; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Println;
          }
        case 70: break;
        case 3: 
          { lexeme=yytext(); valor=-27; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Division;
          }
        case 71: break;
        case 31: 
          { lexeme=yytext(); valor=-37; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Y;
          }
        case 72: break;
        case 14: 
          { lexeme=yytext(); valor=-39; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return P_coma;
          }
        case 73: break;
        case 29: 
          { lexeme=yytext(); valor=-33; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Mayor_igual_que;
          }
        case 74: break;
        case 16: 
          { lexeme=yytext(); valor=-41; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Corchete_c;
          }
        case 75: break;
        case 1: 
          { lexeme=yytext(); valor=0; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return ERROR;
          }
        case 76: break;
        case 32: 
          { lexeme=yytext(); valor=-38; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return O;
          }
        case 77: break;
        case 30: 
          { lexeme=yytext(); valor=-35; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Diferente_que;
          }
        case 78: break;
        case 44: 
          { lexeme=yytext(); valor=-2; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Private;
          }
        case 79: break;
        case 20: 
          { lexeme=yytext(); valor=-45; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Parentesis_c;
          }
        case 80: break;
        case 21: 
          { lexeme=yytext(); valor=-46; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Llave_a;
          }
        case 81: break;
        case 2: 
          { /* Ignorar */
          }
        case 82: break;
        case 18: 
          { lexeme=yytext(); valor=-43; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Dos_puntos;
          }
        case 83: break;
        case 33: 
          { lexeme=yytext(); valor=-5; linea=yyline+1+1; columna=yycolumn+1; posTabla=-1; return Int;
          }
        case 84: break;
        case 41: 
          { lexeme=yytext(); valor=-17; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Switch;
          }
        case 85: break;
        case 43: 
          { lexeme=yytext(); valor=-7; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return String;
          }
        case 86: break;
        case 25: 
          { lexeme=yytext(); valor=-13; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return If;
          }
        case 87: break;
        case 27: 
          { lexeme=yytext(); valor=-34; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Exactamente_igual_que;
          }
        case 88: break;
        case 15: 
          { lexeme=yytext(); valor=-40; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Corchete_a;
          }
        case 89: break;
        case 8: 
          { lexeme=yytext(); valor=-26; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Por;
          }
        case 90: break;
        case 49: 
          { lexeme=yytext(); valor=-11; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return NextDouble;
          }
        case 91: break;
        case 12: 
          { lexeme=yytext(); valor=-32; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Mayor_que;
          }
        case 92: break;
        case 24: 
          { lexeme=yytext(); valor=-21; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return C_real;
          }
        case 93: break;
        case 28: 
          { lexeme=yytext(); valor=-31; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Menor_igual_que;
          }
        case 94: break;
        case 13: 
          { lexeme=yytext(); valor=-36; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return No_es;
          }
        case 95: break;
        case 48: 
          { lexeme=yytext(); valor=-9; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return NextLine;
          }
        case 96: break;
        case 35: 
          { lexeme=yytext(); valor=-18; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Case;
          }
        case 97: break;
        case 40: 
          { lexeme=yytext(); valor=-1; linea=yyline+1; columna=yycolumn+1; posTabla=-1; return Public;
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
