
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun May 05 14:54:06 CST 2024
//----------------------------------------------------

package compiladorapp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NextDouble = 12;
  public static final int Class = 4;
  public static final int No_es = 37;
  public static final int Coma = 48;
  public static final int Y = 38;
  public static final int Llave_c = 47;
  public static final int Double = 7;
  public static final int Llave_a = 46;
  public static final int If = 14;
  public static final int Void = 5;
  public static final int O = 39;
  public static final int Default = 20;
  public static final int C_entera = 22;
  public static final int Menos = 26;
  public static final int C_String = 24;
  public static final int Mas = 25;
  public static final int Else = 15;
  public static final int Mayor_igual_que = 34;
  public static final int Corchete_c = 42;
  public static final int Corchete_a = 41;
  public static final int Por = 27;
  public static final int Diferente_que = 36;
  public static final int While = 17;
  public static final int Division = 28;
  public static final int Int = 6;
  public static final int Menor_igual_que = 32;
  public static final int Parentesis_c = 45;
  public static final int Mayor_que = 33;
  public static final int Modulo = 29;
  public static final int Parentesis_a = 44;
  public static final int P_coma = 40;
  public static final int EOF = 0;
  public static final int NextInt = 11;
  public static final int error = 1;
  public static final int Switch = 18;
  public static final int Private = 3;
  public static final int NextLine = 10;
  public static final int Println = 13;
  public static final int ERROR = 49;
  public static final int Do = 16;
  public static final int Exactamente_igual_que = 35;
  public static final int Case = 19;
  public static final int Public = 2;
  public static final int Dos_puntos = 43;
  public static final int New = 9;
  public static final int String = 8;
  public static final int Menor_que = 31;
  public static final int Identificador = 21;
  public static final int C_real = 23;
  public static final int Igual = 30;
}

